apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name:  ${{ values.name | dump }}
  description: ${{ values.description }}
  annotations:
    backstage.io/managed-by-location: url:https://github.com/${{values.owner}}/${{values.name}}
    backstage.io/managed-by-origin-location: url:https://github.com/${{values.owner}}/${{values.name}}
    tekton.dev/pipelines: ${{values.namespace}}/springboot-pipeline # Namespace/PipelineName
spec:
  type: service
  owner: ${{values.owner | dump}}
  lifecycle: production
