apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name:  ${{ values.name | dump }}
  description: ${{ values.description }}
  annotations:
    backstage.io/managed-by-location: url:https://github.com/${{values.owner}}/${{values.name}}
    backstage.io/managed-by-origin-location: url:https://github.com/${{values.owner}}/${{values.name}}
    tekton.dev/pipelines: ${{values.namespace}}/${{values.name}}-pipeline # Namespace/PipelineName
    backstage.io/kubernetes-id: ${{ values.name | dump }}
    backstage.io/kubernetes-cluster: 'bsidp-cluster'
    backstage.io/kubernetes-namespace: '${{values.namespace}}'
    tektonci/enabled: 'true'
    tektonci/namespace: '${{values.namespace}}'
    # github.com/project-slug: rohit7533/terraform-aks
    # terraform/workspaces: ${{values.workspaceName}} #NodeJSAks
    # terraform/organization: ${{values.org}} 
spec:
  type: service
  owner: ${{values.owner | dump}}
  lifecycle: production
