apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }} #dev-aks-cluster
  annotations:
    github.com/project-slug: kedarbhandare/terraform-aks
    terraform/workspaces: ${{values.workspaceName}} #NodeJSAks
    terraform/organization: ${{values.org}} #kedar-org
  description: Azure Kubernetes Service(AKS) cluster managed by Terraform
  tags:
    - azure
    - aks
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: team-a
